name: web-data-kendaraan

services:
  postgresql:
    image: postgres:latest
    shm_size: 64mb
    container_name: "postgresql"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${POSTGRES_TZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    networks:
      - datakendaraan-networks

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: "pgadmin"
    depends_on:
      - postgresql
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin4/storage
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - datakendaraan-networks

  datakendaraan-api:
    image: datakendaraan-api:latest
    container_name: "datakendaraan-api"
    working_dir: /api-v1
    ports:
      - "8082:8080"
    restart: no
    depends_on:
      - postgresql
    networks:
      datakendaraan-networks:
        aliases:
          - api

  datakendaraan-frontend:
    image: datakendaraan-frontend:latest
    container_name: "datakendaraan-frontend"
    working_dir: /frontend
    ports:
      - "3000:3000"
    restart: no
    networks:
      datakendaraan-networks:
        aliases:
          - web

networks:
  datakendaraan-networks:
    driver: bridge
